spring:
  application:
    name:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  data:
    jdbc:
      repositories:
        enabled:
  sql:
    init:
      platform:
  jdbc:
    dialect:

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable:
  cache:
    type=simple:
jwt:
  secret:
  token-expiration:

logging:
  level:
    org.hibernate.SQL:


